# Simple tensor

In [3]:
import numpy as np

class Tensor (object):
    def __init__(self, data):
        self.data = np.array(data)

    def __add__(self, other):
        return Tensor(self.data + other.data)
    
    def __repr__(self):
        return str(self.data.__repr__())
    
    def __str__(self):
        return str(self.data.__str__())
    

x = Tensor([1, 2, 3, 4, 5])
print(x)

y = x + x
print(y)

[1 2 3 4 5]
[ 2  4  6  8 10]


# Tensor with autograd support.

In [11]:
import numpy as np

# Define a class to represent a tensor
class Tensor (object):
    # Initialize the tensor with data, creators, and creation operation
    def __init__(self, data, creators=None, creation_op=None):
        # Convert the data to a numpy array
        self.data = np.array(data)
        # Store the creation operation (e.g., "add")
        self.creation_op = creation_op
        # Store the creators of this tensor (if any)
        self.creators = creators
        # Initialize the gradient to None
        self.grad = None

    # Perform backpropagation to compute the gradient
    def backward(self, grad):
        # Store the gradient
        self.grad = grad

        # If this tensor was created by an "add" operation
        if (self.creation_op == "add"):
            # Backpropagate the gradient to the creators
            self.creators[0].backward(grad)
            self.creators[1].backward(grad)

    # Overload the "+" operator to add two tensors
    def __add__(self, other):
        # Create a new tensor with the sum of the data
        return Tensor(self.data + other.data, creators=[self, other], creation_op="add")

    # Return a string representation of the tensor
    def __repr__(self):
        return str(self.data.__repr__())

    # Return a string representation of the tensor
    def __str__(self):
        return str(self.data.__str__())

# Create two tensors
x = Tensor([1, 2, 3, 4, 5])
y = Tensor([2, 2, 2, 2, 2])

# Add the two tensors
z = x + y

# Perform backpropagation with a gradient of 1
z.backward(Tensor(np.array([1, 1, 1, 1, 1])))

# Print the gradients of x and y
print(x.grad) 
print(y.grad) 

# Print the creators of z
print(z.creators) 

# Print the creation operation of z
print(z.creation_op)

a = Tensor([1, 2, 3, 4, 5])
b = Tensor([2, 2, 2, 2, 2])
c = Tensor([5, 4, 3, 2, 1])

d = a + b
e = b + c
f = d + e
f.backward(Tensor(np.array([1, 1, 1, 1, 1])))
print(b.grad.data == np.array([2, 2, 2, 2, 2]))

[1 1 1 1 1]
[1 1 1 1 1]
[array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2])]
add
[False False False False False]
