In [8]:
import numpy as np

weights = [0.1 , 0.2, 0]

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)

print(pred)

0.9800000000000001


NumPy Version: Predicting on predictions

In [9]:
import numpy as np

# toes % win # fans

in_wgt = np.array([
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1, 0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1] # hid[2]
]).T

# hid[0] # hid[1] # hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3], #hurt ?
    [0.1, 0.2, 0.0], # win ?
    [0.0, 1.3, 0.1] # sad?
]).T

weights = [in_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])

    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)

print(pred)

[0.2135 0.145  0.5065]


NumPY Real Magic

In [17]:
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0,1,2,3],
              [4,5,6,7]])
d = np.zeros((2,4))
e = np.random.rand(2,5)

print("a * 0.1",a * 0.1)
print("c * 0.2", c * 0.2)
print("a * b", a * b)
print("a * b * 0.2", a * b * 0.2)
print("a * c", a * c)
print("a * e", a * e)

a * 0.1 [0.  0.1 0.2 0.3]
c * 0.2 [[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
a * b [ 0  5 12 21]
a * b * 0.2 [0.  1.  2.4 4.2]
a * c [[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 